# Generated by Django 4.1.7 on 2023-03-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="media")),
                ("url", models.URLField(max_length=1000)),
                ("rank", models.IntegerField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="media")),
                ("rank", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("logo", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=300)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="media")),
                ("post", models.CharField(max_length=300)),
                ("star", models.IntegerField(default=5)),
                ("comment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="media")),
                ("url", models.URLField(max_length=1000)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("logo", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("price", models.ImageField(upload_to="")),
                ("discounted_price", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="media")),
                ("slug", models.TextField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("specification", models.TextField(blank=True)),
                (
                    "labels",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("hot", "hot"),
                            ("sale", "sale"),
                            ("", "default"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("In stock", "In stock"),
                            ("Out of stock", "Out of stock"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.subcategory",
                    ),
                ),
            ],
        ),
    ]
