# Generated by Django 4.1.7 on 2023-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
