# Generated by Django 4.1.7 on 2023-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="star",
            field=models.IntegerField(default=5),
        ),
    ]
