# Generated by Django 4.1.7 on 2023-03-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_cart_checkout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="quntity", new_name="quantity",
        ),
    ]
